### ISSUE TITLE
resource assemblies seem to be missing

### ISSUE THREAD

**Issue by weshaggard** [crummel/source-build-tarball-2.0.5#30] opened 2018-02-03 03:05 UTC
The localized resource assemblies seem to be missing from the SDK.

**Comment by crummel** [comment] 2018-02-05 15:51
I believe we've been intentionally skipping loc stuff in the past, does that sound correct @karajas?

**Comment by karajas** [comment] 2018-02-05 19:05
Yes that's correct.

**Comment by crummel** [comment] 2018-02-13 21:30
Closing as by design.

**Closed as completed by crummel** 2018-02-13 21:30 UTC
